= Keloysius Mak - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: TunedIn
TunedIn is a free-to-use application that brings to you the power of a full-fledged command line personal
organizer, bundled together with a user-friendly interface that keeps all of your information easily accessible and
at your fingertips.

*Code contributed*: [https://github.com/CS2103AUG2017-T14-B2/main/blob/master/collated/main/keloysiusmak.md]
[https://github.com/CS2103AUG2017-T14-B2/main/blob/master/collated/test/keloysiusmak.md]

=== Enhancement Added: Aliases

==== External behavior

---

include::../UserGuide.adoc[tag=alias]

---

==== Justification

Themes make application more visually appealing, enhancing the user experience and user satisfaction when using the
TunedIn application.

==== Implementation

---
include::../DeveloperGuide.adoc[tag=alias]
---

=== Enhancement Added: Theme

==== External behavior

---

include::../UserGuide.adoc[tag=theme]

---

==== Justification

Aliases make operating the application easier and quicker, as users can set their own custom defined
aliases which they can easily remember, and execute commands using our CLI.

==== Implementation

---
include::../DeveloperGuide.adoc[tag=theme]
---

=== Enhancement Proposed: Custom Theme

Allowing users to set their own custom themes will allow them to further personalize TunedIn, which fits in with our
target users, allowing them to add their own dimension for user customizability.

=== Other contributions

* Project and Team Lead
* Updated the design of the application, and edited the backgrounds for the application (Pull requests
https://github.com/CS2103AUG2017-T14-B2/main/pull/61, https://github.com/CS2103AUG2017-T14-B2/main/pull/84)
* Focus on a unified experience for the users, maintained a cohesive UI
