= Xiang TingTing - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: TunedIn
TunedIn is a free-to-use application that brings to you the power of a full-fledged command line personal organizer,
bundled together with a user-friendly interface that keeps all of your information easily accessible and at your fingertips.

*Code contributed*: [https://github.com/CS2103AUG2017-T14-B2/main/blob/master/collated/main/tingtx.md[Functional code]]
[https://github.com/CS2103AUG2017-T14-B2/main/blob/master/collated/test/tingtx.md[Test code]]

=== Enhancement Added:
* Birthday and Group fields to Persons
* Set Email, Birthday to be optional fields.
* Order command to sort with Birthday, Tag and with multiple(2) person fields.(enhanced on the original Order command done by quanle1994)
* Group command to group one or multiple persons in a specified group.
* List command to view a list of person by specified group name.

==== External behavior

---

include::../UserGuide.adoc[tag=order]

---

==== Justification

Ordering is essential to TunedIn. It provides the fundamental and a must-to-have functionality of an organizer.
With the ordering mechanism, user will be able to order the list of contacts in 14 different ways. This
is inline with our goal in making TunedIn as customizable as possible
and, most importantly to allow the user to organize the contacts to their most preferred way.

==== Implementation

---

include::../DeveloperGuide.adoc[tag=order]

---

==== External behavior

---

include::../UserGuide.adoc[tag=group]

---

==== Justification

Group mechanism is another essential function of TunedIn. It allows the user to organize the
contacts to user specified groups.

==== Implementation

---

include::../DeveloperGuide.adoc[tag=group]

---

==== External behavior

---

include::../UserGuide.adoc[tag=list]

---

==== Justification

List can be used to show the entire list of contacts.
It is further enhanced to complement the function of group by allowing user to
view a list of contacts by group. Instead of implementing the group list view function
in the group function, it is more intuitive for the user to typed `list` followed by group
name.

==== Implementation

---


---


=== Enhancement Proposed:



=== Other contributions

* Updated the person card with birthday (Pull requests https://github.com[#33], https://github.com[#34])
* Updated the person card with group ()
